import type {
  DashboardKPIs,
  DepartmentSummary,
  Employee,
  PerformanceMetrics,
  PerformanceTrend,
} from "@/types/employee";

export const mockEmployees: Employee[] = [
  {
    id: "emp-001",
    name: "Sarah Chen",
    email: "sarah.chen@company.com",
    role: "Senior Engineer",
    department: "Engineering",
    joinDate: "2021-03-15",
    status: "active",
  },
  {
    id: "emp-002",
    name: "Marcus Johnson",
    email: "marcus.j@company.com",
    role: "Product Manager",
    department: "Product",
    joinDate: "2020-07-22",
    status: "active",
  },
  {
    id: "emp-003",
    name: "Emily Rodriguez",
    email: "emily.r@company.com",
    role: "UX Designer",
    department: "Design",
    joinDate: "2022-01-10",
    status: "active",
  },
  {
    id: "emp-004",
    name: "David Kim",
    email: "david.kim@company.com",
    role: "Engineering Lead",
    department: "Engineering",
    joinDate: "2019-11-05",
    status: "active",
  },
  {
    id: "emp-005",
    name: "Lisa Thompson",
    email: "lisa.t@company.com",
    role: "Marketing Manager",
    department: "Marketing",
    joinDate: "2021-08-30",
    status: "active",
  },
  {
    id: "emp-006",
    name: "James Wilson",
    email: "james.w@company.com",
    role: "Sales Representative",
    department: "Sales",
    joinDate: "2022-04-18",
    status: "on-leave",
  },
  {
    id: "emp-007",
    name: "Anna Petrov",
    email: "anna.p@company.com",
    role: "Data Analyst",
    department: "Engineering",
    joinDate: "2021-12-01",
    status: "active",
  },
  {
    id: "emp-008",
    name: "Michael Brown",
    email: "michael.b@company.com",
    role: "HR Specialist",
    department: "HR",
    joinDate: "2020-05-14",
    status: "active",
  },
  {
    id: "emp-009",
    name: "Sophie Martinez",
    email: "sophie.m@company.com",
    role: "Content Strategist",
    department: "Marketing",
    joinDate: "2022-09-20",
    status: "active",
  },
  {
    id: "emp-010",
    name: "Robert Taylor",
    email: "robert.t@company.com",
    role: "DevOps Engineer",
    department: "Engineering",
    joinDate: "2020-02-28",
    status: "active",
  },
  {
    id: "emp-011",
    name: "Jennifer Lee",
    email: "jen.lee@company.com",
    role: "QA Engineer",
    department: "Engineering",
    joinDate: "2021-06-15",
    status: "active",
  },
  {
    id: "emp-012",
    name: "Christopher Davis",
    email: "chris.d@company.com",
    role: "Account Executive",
    department: "Sales",
    joinDate: "2022-03-08",
    status: "active",
  },
];

export const mockPerformanceMetrics: PerformanceMetrics[] = [
  {
    employeeId: "emp-001",
    period: "2024-Q1",
    score: 92,
    attendance: 98,
    tasksCompleted: 45,
    tasksTotal: 48,
    peerReview: 88,
    selfReview: 90,
  },
  {
    employeeId: "emp-001",
    period: "2024-Q2",
    score: 94,
    attendance: 96,
    tasksCompleted: 50,
    tasksTotal: 52,
    peerReview: 92,
    selfReview: 91,
  },
  {
    employeeId: "emp-001",
    period: "2024-Q3",
    score: 89,
    attendance: 94,
    tasksCompleted: 42,
    tasksTotal: 45,
    peerReview: 85,
    selfReview: 88,
  },
  {
    employeeId: "emp-001",
    period: "2024-Q4",
    score: 96,
    attendance: 99,
    tasksCompleted: 55,
    tasksTotal: 56,
    peerReview: 94,
    selfReview: 93,
  },
  {
    employeeId: "emp-002",
    period: "2024-Q1",
    score: 88,
    attendance: 95,
    tasksCompleted: 38,
    tasksTotal: 42,
    peerReview: 90,
    selfReview: 87,
  },
  {
    employeeId: "emp-002",
    period: "2024-Q2",
    score: 91,
    attendance: 97,
    tasksCompleted: 44,
    tasksTotal: 46,
    peerReview: 89,
    selfReview: 92,
  },
  {
    employeeId: "emp-002",
    period: "2024-Q3",
    score: 87,
    attendance: 93,
    tasksCompleted: 40,
    tasksTotal: 44,
    peerReview: 86,
    selfReview: 88,
  },
  {
    employeeId: "emp-002",
    period: "2024-Q4",
    score: 93,
    attendance: 98,
    tasksCompleted: 48,
    tasksTotal: 50,
    peerReview: 91,
    selfReview: 90,
  },
  {
    employeeId: "emp-003",
    period: "2024-Q1",
    score: 85,
    attendance: 92,
    tasksCompleted: 35,
    tasksTotal: 40,
    peerReview: 82,
    selfReview: 84,
  },
  {
    employeeId: "emp-003",
    period: "2024-Q2",
    score: 89,
    attendance: 94,
    tasksCompleted: 42,
    tasksTotal: 45,
    peerReview: 87,
    selfReview: 86,
  },
  {
    employeeId: "emp-003",
    period: "2024-Q3",
    score: 91,
    attendance: 96,
    tasksCompleted: 46,
    tasksTotal: 48,
    peerReview: 90,
    selfReview: 89,
  },
  {
    employeeId: "emp-003",
    period: "2024-Q4",
    score: 88,
    attendance: 93,
    tasksCompleted: 40,
    tasksTotal: 44,
    peerReview: 85,
    selfReview: 87,
  },
  {
    employeeId: "emp-004",
    period: "2024-Q1",
    score: 95,
    attendance: 99,
    tasksCompleted: 52,
    tasksTotal: 54,
    peerReview: 94,
    selfReview: 95,
  },
  {
    employeeId: "emp-004",
    period: "2024-Q2",
    score: 97,
    attendance: 100,
    tasksCompleted: 58,
    tasksTotal: 58,
    peerReview: 96,
    selfReview: 96,
  },
  {
    employeeId: "emp-004",
    period: "2024-Q3",
    score: 93,
    attendance: 97,
    tasksCompleted: 50,
    tasksTotal: 52,
    peerReview: 92,
    selfReview: 93,
  },
  {
    employeeId: "emp-004",
    period: "2024-Q4",
    score: 98,
    attendance: 100,
    tasksCompleted: 60,
    tasksTotal: 60,
    peerReview: 97,
    selfReview: 98,
  },
  {
    employeeId: "emp-005",
    period: "2024-Q1",
    score: 86,
    attendance: 94,
    tasksCompleted: 36,
    tasksTotal: 40,
    peerReview: 84,
    selfReview: 85,
  },
  {
    employeeId: "emp-005",
    period: "2024-Q2",
    score: 90,
    attendance: 96,
    tasksCompleted: 42,
    tasksTotal: 44,
    peerReview: 88,
    selfReview: 89,
  },
  {
    employeeId: "emp-005",
    period: "2024-Q3",
    score: 88,
    attendance: 93,
    tasksCompleted: 38,
    tasksTotal: 42,
    peerReview: 86,
    selfReview: 87,
  },
  {
    employeeId: "emp-005",
    period: "2024-Q4",
    score: 92,
    attendance: 97,
    tasksCompleted: 46,
    tasksTotal: 48,
    peerReview: 90,
    selfReview: 91,
  },
  {
    employeeId: "emp-006",
    period: "2024-Q1",
    score: 82,
    attendance: 88,
    tasksCompleted: 32,
    tasksTotal: 38,
    peerReview: 80,
    selfReview: 81,
  },
  {
    employeeId: "emp-006",
    period: "2024-Q2",
    score: 85,
    attendance: 90,
    tasksCompleted: 36,
    tasksTotal: 40,
    peerReview: 83,
    selfReview: 84,
  },
  {
    employeeId: "emp-007",
    period: "2024-Q1",
    score: 90,
    attendance: 96,
    tasksCompleted: 44,
    tasksTotal: 46,
    peerReview: 88,
    selfReview: 89,
  },
  {
    employeeId: "emp-007",
    period: "2024-Q2",
    score: 92,
    attendance: 97,
    tasksCompleted: 48,
    tasksTotal: 50,
    peerReview: 91,
    selfReview: 90,
  },
  {
    employeeId: "emp-007",
    period: "2024-Q3",
    score: 89,
    attendance: 95,
    tasksCompleted: 42,
    tasksTotal: 45,
    peerReview: 87,
    selfReview: 88,
  },
  {
    employeeId: "emp-007",
    period: "2024-Q4",
    score: 94,
    attendance: 98,
    tasksCompleted: 50,
    tasksTotal: 52,
    peerReview: 93,
    selfReview: 92,
  },
  {
    employeeId: "emp-008",
    period: "2024-Q1",
    score: 87,
    attendance: 95,
    tasksCompleted: 38,
    tasksTotal: 42,
    peerReview: 85,
    selfReview: 86,
  },
  {
    employeeId: "emp-008",
    period: "2024-Q2",
    score: 89,
    attendance: 96,
    tasksCompleted: 42,
    tasksTotal: 44,
    peerReview: 88,
    selfReview: 87,
  },
  {
    employeeId: "emp-008",
    period: "2024-Q3",
    score: 91,
    attendance: 97,
    tasksCompleted: 46,
    tasksTotal: 48,
    peerReview: 90,
    selfReview: 89,
  },
  {
    employeeId: "emp-008",
    period: "2024-Q4",
    score: 88,
    attendance: 94,
    tasksCompleted: 40,
    tasksTotal: 44,
    peerReview: 86,
    selfReview: 87,
  },
  {
    employeeId: "emp-009",
    period: "2024-Q1",
    score: 84,
    attendance: 93,
    tasksCompleted: 34,
    tasksTotal: 40,
    peerReview: 82,
    selfReview: 83,
  },
  {
    employeeId: "emp-009",
    period: "2024-Q2",
    score: 87,
    attendance: 95,
    tasksCompleted: 40,
    tasksTotal: 44,
    peerReview: 85,
    selfReview: 86,
  },
  {
    employeeId: "emp-009",
    period: "2024-Q3",
    score: 90,
    attendance: 96,
    tasksCompleted: 44,
    tasksTotal: 46,
    peerReview: 88,
    selfReview: 89,
  },
  {
    employeeId: "emp-009",
    period: "2024-Q4",
    score: 86,
    attendance: 94,
    tasksCompleted: 38,
    tasksTotal: 42,
    peerReview: 84,
    selfReview: 85,
  },
  {
    employeeId: "emp-010",
    period: "2024-Q1",
    score: 93,
    attendance: 97,
    tasksCompleted: 48,
    tasksTotal: 50,
    peerReview: 91,
    selfReview: 92,
  },
  {
    employeeId: "emp-010",
    period: "2024-Q2",
    score: 95,
    attendance: 98,
    tasksCompleted: 52,
    tasksTotal: 54,
    peerReview: 94,
    selfReview: 93,
  },
  {
    employeeId: "emp-010",
    period: "2024-Q3",
    score: 91,
    attendance: 96,
    tasksCompleted: 46,
    tasksTotal: 48,
    peerReview: 89,
    selfReview: 90,
  },
  {
    employeeId: "emp-010",
    period: "2024-Q4",
    score: 96,
    attendance: 99,
    tasksCompleted: 56,
    tasksTotal: 56,
    peerReview: 95,
    selfReview: 94,
  },
  {
    employeeId: "emp-011",
    period: "2024-Q1",
    score: 88,
    attendance: 95,
    tasksCompleted: 40,
    tasksTotal: 44,
    peerReview: 86,
    selfReview: 87,
  },
  {
    employeeId: "emp-011",
    period: "2024-Q2",
    score: 90,
    attendance: 96,
    tasksCompleted: 44,
    tasksTotal: 46,
    peerReview: 89,
    selfReview: 88,
  },
  {
    employeeId: "emp-011",
    period: "2024-Q3",
    score: 87,
    attendance: 94,
    tasksCompleted: 40,
    tasksTotal: 44,
    peerReview: 85,
    selfReview: 86,
  },
  {
    employeeId: "emp-011",
    period: "2024-Q4",
    score: 92,
    attendance: 97,
    tasksCompleted: 48,
    tasksTotal: 50,
    peerReview: 91,
    selfReview: 90,
  },
  {
    employeeId: "emp-012",
    period: "2024-Q1",
    score: 81,
    attendance: 90,
    tasksCompleted: 30,
    tasksTotal: 38,
    peerReview: 78,
    selfReview: 80,
  },
  {
    employeeId: "emp-012",
    period: "2024-Q2",
    score: 84,
    attendance: 92,
    tasksCompleted: 36,
    tasksTotal: 40,
    peerReview: 82,
    selfReview: 83,
  },
  {
    employeeId: "emp-012",
    period: "2024-Q3",
    score: 86,
    attendance: 94,
    tasksCompleted: 40,
    tasksTotal: 44,
    peerReview: 84,
    selfReview: 85,
  },
  {
    employeeId: "emp-012",
    period: "2024-Q4",
    score: 89,
    attendance: 95,
    tasksCompleted: 44,
    tasksTotal: 46,
    peerReview: 87,
    selfReview: 88,
  },
];

export const mockDepartmentSummaries: DepartmentSummary[] = [
  {
    department: "Engineering",
    employeeCount: 5,
    avgPerformance: 92.4,
    avgAttendance: 96.8,
    totalTasksCompleted: 241,
    totalTasks: 252,
  },
  {
    department: "Product",
    employeeCount: 1,
    avgPerformance: 89.8,
    avgAttendance: 95.8,
    totalTasksCompleted: 170,
    totalTasks: 182,
  },
  {
    department: "Design",
    employeeCount: 1,
    avgPerformance: 88.3,
    avgAttendance: 93.8,
    totalTasksCompleted: 163,
    totalTasks: 177,
  },
  {
    department: "Marketing",
    employeeCount: 2,
    avgPerformance: 88.0,
    avgAttendance: 95.0,
    totalTasksCompleted: 164,
    totalTasks: 180,
  },
  {
    department: "Sales",
    employeeCount: 2,
    avgPerformance: 84.5,
    avgAttendance: 91.0,
    totalTasksCompleted: 140,
    totalTasks: 164,
  },
  {
    department: "HR",
    employeeCount: 1,
    avgPerformance: 89.0,
    avgAttendance: 95.5,
    totalTasksCompleted: 166,
    totalTasks: 178,
  },
];

export const mockDashboardKPIs: DashboardKPIs = {
  totalEmployees: 12,
  avgPerformanceScore: 89.2,
  attendanceRate: 94.8,
  taskCompletionRate: 92.5,
  activeEmployees: 11,
  onLeaveEmployees: 1,
};

export const mockPerformanceTrends: PerformanceTrend[] = [
  { period: "2024-Q1", avgScore: 87.5, topPerformer: "David Kim" },
  { period: "2024-Q2", avgScore: 89.8, topPerformer: "David Kim" },
  { period: "2024-Q3", avgScore: 88.2, topPerformer: "David Kim" },
  { period: "2024-Q4", avgScore: 91.5, topPerformer: "David Kim" },
];
