/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DashboardKPIs {
  'totalEmployees' : bigint,
  'avgOverallScore' : number,
  'topDepartment' : string,
  'avgTaskCompletionRate' : number,
  'avgAttendanceRate' : number,
}
export interface DepartmentSummary {
  'avgAttendance' : number,
  'employeeCount' : bigint,
  'department' : string,
  'avgPerformance' : number,
}
export interface Employee {
  'id' : UserId,
  'joinDate' : Timestamp,
  'name' : string,
  'role' : string,
  'email' : string,
  'department' : string,
  'avatar' : [] | [string],
}
export interface PerformanceMetrics {
  'overallScore' : number,
  'productivityScore' : number,
  'period' : string,
  'qualityScore' : number,
  'taskCompletionRate' : number,
  'attendanceRate' : number,
  'employeeId' : UserId,
}
export type Timestamp = bigint;
export type UserId = bigint;
export interface _SERVICE {
  '__employees' : ActorMethod<[[] | [bigint], [] | [bigint]], Array<Employee>>,
  '__metrics' : ActorMethod<
    [[] | [bigint], [] | [bigint]],
    Array<PerformanceMetrics>
  >,
  '__nextEmployeeId' : ActorMethod<[], UserId>,
  'addEmployee' : ActorMethod<
    [string, string, string, string, Timestamp, [] | [string]],
    Employee
  >,
  'addPerformanceMetrics' : ActorMethod<[PerformanceMetrics], undefined>,
  'getAllEmployees' : ActorMethod<[], Array<Employee>>,
  'getDashboardKPIs' : ActorMethod<[], DashboardKPIs>,
  'getDepartmentSummaries' : ActorMethod<[], Array<DepartmentSummary>>,
  'getEmployeeById' : ActorMethod<[UserId], [] | [Employee]>,
  'getEmployeesByDepartment' : ActorMethod<[string], Array<Employee>>,
  'getPerformanceMetrics' : ActorMethod<[UserId], Array<PerformanceMetrics>>,
  'updateEmployee' : ActorMethod<[Employee], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];