/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserId = IDL.Nat;
export const Timestamp = IDL.Int;
export const Employee = IDL.Record({
  'id' : UserId,
  'joinDate' : Timestamp,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'email' : IDL.Text,
  'department' : IDL.Text,
  'avatar' : IDL.Opt(IDL.Text),
});
export const PerformanceMetrics = IDL.Record({
  'overallScore' : IDL.Float64,
  'productivityScore' : IDL.Float64,
  'period' : IDL.Text,
  'qualityScore' : IDL.Float64,
  'taskCompletionRate' : IDL.Float64,
  'attendanceRate' : IDL.Float64,
  'employeeId' : UserId,
});
export const DashboardKPIs = IDL.Record({
  'totalEmployees' : IDL.Nat,
  'avgOverallScore' : IDL.Float64,
  'topDepartment' : IDL.Text,
  'avgTaskCompletionRate' : IDL.Float64,
  'avgAttendanceRate' : IDL.Float64,
});
export const DepartmentSummary = IDL.Record({
  'avgAttendance' : IDL.Float64,
  'employeeCount' : IDL.Nat,
  'department' : IDL.Text,
  'avgPerformance' : IDL.Float64,
});

export const idlService = IDL.Service({
  '__employees' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(Employee)],
      ['query'],
    ),
  '__metrics' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(PerformanceMetrics)],
      ['query'],
    ),
  '__nextEmployeeId' : IDL.Func([], [UserId], ['query']),
  'addEmployee' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, Timestamp, IDL.Opt(IDL.Text)],
      [Employee],
      [],
    ),
  'addPerformanceMetrics' : IDL.Func([PerformanceMetrics], [], []),
  'getAllEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
  'getDashboardKPIs' : IDL.Func([], [DashboardKPIs], ['query']),
  'getDepartmentSummaries' : IDL.Func(
      [],
      [IDL.Vec(DepartmentSummary)],
      ['query'],
    ),
  'getEmployeeById' : IDL.Func([UserId], [IDL.Opt(Employee)], ['query']),
  'getEmployeesByDepartment' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Employee)],
      ['query'],
    ),
  'getPerformanceMetrics' : IDL.Func(
      [UserId],
      [IDL.Vec(PerformanceMetrics)],
      ['query'],
    ),
  'updateEmployee' : IDL.Func([Employee], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserId = IDL.Nat;
  const Timestamp = IDL.Int;
  const Employee = IDL.Record({
    'id' : UserId,
    'joinDate' : Timestamp,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'email' : IDL.Text,
    'department' : IDL.Text,
    'avatar' : IDL.Opt(IDL.Text),
  });
  const PerformanceMetrics = IDL.Record({
    'overallScore' : IDL.Float64,
    'productivityScore' : IDL.Float64,
    'period' : IDL.Text,
    'qualityScore' : IDL.Float64,
    'taskCompletionRate' : IDL.Float64,
    'attendanceRate' : IDL.Float64,
    'employeeId' : UserId,
  });
  const DashboardKPIs = IDL.Record({
    'totalEmployees' : IDL.Nat,
    'avgOverallScore' : IDL.Float64,
    'topDepartment' : IDL.Text,
    'avgTaskCompletionRate' : IDL.Float64,
    'avgAttendanceRate' : IDL.Float64,
  });
  const DepartmentSummary = IDL.Record({
    'avgAttendance' : IDL.Float64,
    'employeeCount' : IDL.Nat,
    'department' : IDL.Text,
    'avgPerformance' : IDL.Float64,
  });
  
  return IDL.Service({
    '__employees' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(Employee)],
        ['query'],
      ),
    '__metrics' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(PerformanceMetrics)],
        ['query'],
      ),
    '__nextEmployeeId' : IDL.Func([], [UserId], ['query']),
    'addEmployee' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, Timestamp, IDL.Opt(IDL.Text)],
        [Employee],
        [],
      ),
    'addPerformanceMetrics' : IDL.Func([PerformanceMetrics], [], []),
    'getAllEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
    'getDashboardKPIs' : IDL.Func([], [DashboardKPIs], ['query']),
    'getDepartmentSummaries' : IDL.Func(
        [],
        [IDL.Vec(DepartmentSummary)],
        ['query'],
      ),
    'getEmployeeById' : IDL.Func([UserId], [IDL.Opt(Employee)], ['query']),
    'getEmployeesByDepartment' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Employee)],
        ['query'],
      ),
    'getPerformanceMetrics' : IDL.Func(
        [UserId],
        [IDL.Vec(PerformanceMetrics)],
        ['query'],
      ),
    'updateEmployee' : IDL.Func([Employee], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };