/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface DepartmentSummary {
    avgAttendance: number;
    employeeCount: bigint;
    department: string;
    avgPerformance: number;
}
export type UserId = bigint;
export type Timestamp = bigint;
export interface Employee {
    id: UserId;
    joinDate: Timestamp;
    name: string;
    role: string;
    email: string;
    department: string;
    avatar?: string;
}
export interface DashboardKPIs {
    totalEmployees: bigint;
    avgOverallScore: number;
    topDepartment: string;
    avgTaskCompletionRate: number;
    avgAttendanceRate: number;
}
export interface PerformanceMetrics {
    overallScore: number;
    productivityScore: number;
    period: string;
    qualityScore: number;
    taskCompletionRate: number;
    attendanceRate: number;
    employeeId: UserId;
}
export interface backendInterface {
    __employees(io: bigint | null, count: bigint | null): Promise<Array<Employee>>;
    __metrics(io: bigint | null, count: bigint | null): Promise<Array<PerformanceMetrics>>;
    __nextEmployeeId(): Promise<UserId>;
    addEmployee(name: string, email: string, department: string, role: string, joinDate: Timestamp, avatar: string | null): Promise<Employee>;
    addPerformanceMetrics(entry: PerformanceMetrics): Promise<void>;
    getAllEmployees(): Promise<Array<Employee>>;
    getDashboardKPIs(): Promise<DashboardKPIs>;
    getDepartmentSummaries(): Promise<Array<DepartmentSummary>>;
    getEmployeeById(id: UserId): Promise<Employee | null>;
    getEmployeesByDepartment(department: string): Promise<Array<Employee>>;
    getPerformanceMetrics(employeeId: UserId): Promise<Array<PerformanceMetrics>>;
    updateEmployee(employee: Employee): Promise<boolean>;
}
import type { Employee as _Employee, Timestamp as _Timestamp, UserId as _UserId } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async __employees(arg0: bigint | null, arg1: bigint | null): Promise<Array<Employee>> {
        if (this.processError) {
            try {
                const result = await this.actor.__employees(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__employees(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async __metrics(arg0: bigint | null, arg1: bigint | null): Promise<Array<PerformanceMetrics>> {
        if (this.processError) {
            try {
                const result = await this.actor.__metrics(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__metrics(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async __nextEmployeeId(): Promise<UserId> {
        if (this.processError) {
            try {
                const result = await this.actor.__nextEmployeeId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__nextEmployeeId();
            return result;
        }
    }
    async addEmployee(arg0: string, arg1: string, arg2: string, arg3: string, arg4: Timestamp, arg5: string | null): Promise<Employee> {
        if (this.processError) {
            try {
                const result = await this.actor.addEmployee(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n6(this._uploadFile, this._downloadFile, arg5));
                return from_candid_Employee_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEmployee(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n6(this._uploadFile, this._downloadFile, arg5));
            return from_candid_Employee_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async addPerformanceMetrics(arg0: PerformanceMetrics): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPerformanceMetrics(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPerformanceMetrics(arg0);
            return result;
        }
    }
    async getAllEmployees(): Promise<Array<Employee>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEmployees();
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEmployees();
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardKPIs(): Promise<DashboardKPIs> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardKPIs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardKPIs();
            return result;
        }
    }
    async getDepartmentSummaries(): Promise<Array<DepartmentSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDepartmentSummaries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDepartmentSummaries();
            return result;
        }
    }
    async getEmployeeById(arg0: UserId): Promise<Employee | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmployeeById(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmployeeById(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEmployeesByDepartment(arg0: string): Promise<Array<Employee>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmployeesByDepartment(arg0);
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmployeesByDepartment(arg0);
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPerformanceMetrics(arg0: UserId): Promise<Array<PerformanceMetrics>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPerformanceMetrics(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPerformanceMetrics(arg0);
            return result;
        }
    }
    async updateEmployee(arg0: Employee): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEmployee(to_candid_Employee_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEmployee(to_candid_Employee_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_Employee_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Employee): Employee {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Employee]): Employee | null {
    return value.length === 0 ? null : from_candid_Employee_n3(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    joinDate: _Timestamp;
    name: string;
    role: string;
    email: string;
    department: string;
    avatar: [] | [string];
}): {
    id: UserId;
    joinDate: Timestamp;
    name: string;
    role: string;
    email: string;
    department: string;
    avatar?: string;
} {
    return {
        id: value.id,
        joinDate: value.joinDate,
        name: value.name,
        role: value.role,
        email: value.email,
        department: value.department,
        avatar: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.avatar))
    };
}
function from_candid_vec_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Employee>): Array<Employee> {
    return value.map((x)=>from_candid_Employee_n3(_uploadFile, _downloadFile, x));
}
function to_candid_Employee_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Employee): _Employee {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: UserId;
    joinDate: Timestamp;
    name: string;
    role: string;
    email: string;
    department: string;
    avatar?: string;
}): {
    id: _UserId;
    joinDate: _Timestamp;
    name: string;
    role: string;
    email: string;
    department: string;
    avatar: [] | [string];
} {
    return {
        id: value.id,
        joinDate: value.joinDate,
        name: value.name,
        role: value.role,
        email: value.email,
        department: value.department,
        avatar: value.avatar ? candid_some(value.avatar) : candid_none()
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
